# Generated by Django 2.0.3 on 2018-03-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
       migrations.RunSQL(
           "DROP VIEW IF EXISTS crypto_coin_information;"
        ),
         migrations.CreateModel(
            name='CryptoCoinInformation',
            fields=[
                ('id', models.IntegerField()),
                ('rank', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('market_cap', models.BigIntegerField(verbose_name=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume_24hr', models.BigIntegerField(verbose_name=20)),
                ('change_1hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_24hr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency_detail', models.TextField()),
                ('coin_newsFeed', models.TextField()),
            ],
            options={
                'db_table': 'crypto_coin_information',
                'managed': False,
            },
        ),
    ]
